version: "3.8"
services:
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: django-redis
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/redis/data:/data
      - ./docker/redis/logs:/var/log/redis
      - ./docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    sysctls:
      - net.core.somaxconn=1024
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "redis-server /usr/local/etc/redis/redis.conf --requirepass ${DJANGO_REDIS_PASSWORD} --loglevel ${DJANGO_REDIS_LOG_LEVEL}",
      ]
