version: '3.1'

services:
  django-db:
    image: postgres:13.4
    container_name: django-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
      # - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - django-net

volumes:
  pgdata:

networks:
  django-net:
    driver: bridge
