version: '3.1'

services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django
    entrypoint: './entrypoint.sh'
    # platform: linux/amd64
    restart: always
    depends_on:
      - django-db
    env_file: .env
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      DEV: ${DEV}
    ports:
      - 3003:3003
    volumes:
      - ./backend:/home/appuser/app/django
      - ./Pipfile:/home/appuser/app/Pipfile
      # - ./Pipfile.lock:/home/appuser/app/Pipfile.lock
      - ./backend/static_collected:/django/static_collected
      - ./uwsgi.ini:/home/appuser/app/uwsgi.ini
      - uwsgi-log:/tmp
    networks:
      - django-net

  django-nginx:
    container_name: django-nginx
    image: nginx
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    # ports:
    #   - 3002:3002
    volumes:
      - ./backend/media:/django/media
      - ./backend/static_collected:/django/static_collected
    restart: always
    depends_on:
      - django
    networks:
      - django-net

  django-db:
    image: postgres:14.5
    container_name: django-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - django-net

volumes:
  pgdata:
  uwsgi-log:

networks:
  django-net:
    driver: bridge

