version: '3.1'

services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django
    entrypoint: './entrypoint.sh'
    # platform: linux/amd64
    restart: always
    depends_on:
      - django-db
    env_file: .env
    environment:
      DEV: ${DEV}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    # ports:
    #   - 3003:3003
    volumes:
      - ./backend:/home/appuser/app/django
      - ./Pipfile:/home/appuser/app/Pipfile
      # - ./Pipfile.lock:/home/appuser/app/Pipfile.lock
      - ./backend/static_collected:/django/static_collected
      - ./uwsgi.ini:/home/appuser/app/uwsgi.ini
      - uwsgi-log:/tmp
    networks:
      - django-net

  django-nginx:
    container_name: django-nginx
    image: nginx
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backend/media:/django/media
      - ./backend/dist/static:/django/dist/static
      - ./backend/static_collected:/django/static_collected
    restart: always
    depends_on:
      - django
    networks:
      - django-net

  django-db:
    image: postgres:14.5
    container_name: django-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # PGDATA: /var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pgdata:/var/lib/postgresql/data/
    networks:
      - django-net

  django-redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    restart: always
    container_name: django-redis
    env_file:
      - .env
    # ports:
    #   - "6379:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/redis/data:/data
      - ./docker/redis/logs:/var/log/redis
      - ./docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    sysctls:
      - net.core.somaxconn=1024
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "redis-server /usr/local/etc/redis/redis.conf --requirepass ${DJANGO_REDIS_PASSWORD} --loglevel ${DJANGO_REDIS_LOG_LEVEL} --logfile ''",
      ]
    networks:
      - django-net

volumes:
  pgdata:
  uwsgi-log:

networks:
  django-net:
    driver: bridge

