# Generated by Django 4.1.2 on 2022-10-26 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最後更新時間"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatar/%Y-%m-%d/",
                        verbose_name="大頭照",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="姓名"
                    ),
                ),
                ("birth", models.DateField(blank=True, null=True, verbose_name="生日")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "男"), ("female", "女")],
                        max_length=16,
                        null=True,
                        verbose_name="性別",
                    ),
                ),
                (
                    "identity",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        unique=True,
                        verbose_name="身分證字號",
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="住家電話"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="行動電話"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="聯絡地址"
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="備註")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
