"""
Django settings for project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ

env = environ.Env(
    DEBUG=(bool, False),
    STRESS_TEST=(bool, False),
    ALLOWED_HOSTS=(list, []),
    DJANGO_REDIS_ENABLE=(bool, False),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Read env file
environ.Env.read_env(BASE_DIR.parent / ".env")

# DEV dev/stage/prod
DEV = env("DEV")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")


# Application definition
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
]

THIRD_PARTY_APPS = [
    "sass_processor",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    # "drf_yasg",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "corsheaders",
    "registry",
    "compressor",
    # Oauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "rolepermissions",
    # partition table
    # "psqlextra",
    "django_celery_results",
    "django_celery_beat",
    "django_filters",
]

LOCAL_APPS = [
    "log",
    "base",
    "api",
    "myapp",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "django_base.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "dist"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
            ],
        },
    },
]

WSGI_APPLICATION = "django_base.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "zh-hant"

TIME_ZONE = "Asia/Taipei"

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGE_COOKIE_NAME = "locale"

LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


STATIC_URL = "static_collected/"

# 前後端整合 key: value 對應 url: path
FRONTEND_STATIC_ROOT = {
    "static/": os.path.join(BASE_DIR, "dist/static"),
    "icons/": os.path.join(BASE_DIR, "dist/icons"),
    "imgs/": os.path.join(BASE_DIR, "dist/imgs"),
    "favicon.ico/": os.path.join(BASE_DIR, "dist/favicon.ico"),
}

STATIC_ROOT = BASE_DIR / "static_collected"

MEDIA_URL = "media/"

MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django Compressor & SASS processor
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "sass_processor.finders.CssFinder",
]

# SASS_PROCESSOR_INCLUDE_DIRS = []

# Authentication api
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
        # "rest_framework.authentication.SessionAuthentication"
        # "rest_framework.authentication.BasicAuthentication",
        # "rest_framework.authentication.TokenAuthentication",
    ),
}

# JWT
REST_AUTH = {
    # "LOGIN_SERIALIZER": "dj_rest_auth.serializers.LoginSerializer",
    # "TOKEN_SERIALIZER": "dj_rest_auth.serializers.TokenSerializer",
    # "JWT_SERIALIZER": "dj_rest_auth.serializers.JWTSerializer",
    # "JWT_SERIALIZER_WITH_EXPIRATION": "dj_rest_auth.serializers.JWTSerializerWithExpiration",
    # "JWT_TOKEN_CLAIMS_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    # "USER_DETAILS_SERIALIZER": "dj_rest_auth.serializers.UserDetailsSerializer",
    # "PASSWORD_RESET_SERIALIZER": "dj_rest_auth.serializers.PasswordResetSerializer",
    # "PASSWORD_RESET_CONFIRM_SERIALIZER": "dj_rest_auth.serializers.PasswordResetConfirmSerializer",
    # "PASSWORD_CHANGE_SERIALIZER": "dj_rest_auth.serializers.PasswordChangeSerializer",
    # "REGISTER_SERIALIZER": "dj_rest_auth.registration.serializers.RegisterSerializer",
    # "REGISTER_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
    # "TOKEN_MODEL": "rest_framework.authtoken.models.Token",
    # "TOKEN_CREATOR": "dj_rest_auth.utils.default_create_token",
    # "PASSWORD_RESET_USE_SITES_DOMAIN": False,
    "SESSION_LOGIN": True,
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "jwt-auth",
    "JWT_AUTH_REFRESH_COOKIE": "jwt-refresh-token",
    "JWT_AUTH_REFRESH_COOKIE_PATH": "/",
    "JWT_AUTH_SECURE": False,
    "JWT_AUTH_HTTPONLY": False,
    # "JWT_AUTH_SAMESITE": "Lax",
    # "JWT_AUTH_RETURN_EXPIRATION": False,
    # "OLD_PASSWORD_FIELD_ENABLED": False,
    # "LOGOUT_ON_PASSWORD_CHANGE": False,
    # "JWT_AUTH_COOKIE_USE_CSRF": False,
    # "JWT_AUTH_COOKIE_ENFORCE_CSRF_ON_UNAUTHENTICATED": False,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=24),
    "ROTATE_REFRESH_TOKENS": True,  # refresh token 每次登入都會更新
    "BLACKLIST_AFTER_ROTATION": True,  # refresh token 更新後，將舊的 refresh token 加入黑名單
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# All-Auth
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# This setting determines whether the username is stored in lowercase (False) or whether its casing is to be preserved (True). Note that when casing is preserved, potentially expensive __iexact lookups are performed when filter on username. For now, the default is set to True to maintain backwards compatibility.
ACCOUNT_PRESERVE_USERNAME_CASING = False

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
)

SITE_ID = 1

ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_UNIQUE_EMAIL = True
# to use old_password.
OLD_PASSWORD_FIELD_ENABLED = True
# to keep the user logged in after password change
LOGOUT_ON_PASSWORD_CHANGE = False

# Mail service
# SMTP Configuration
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"  # SMTP伺服器
# EMAIL_PORT = 587  # TLS通訊埠號
# EMAIL_USE_TLS = True  # 開啟TLS(傳輸層安全性)
# EMAIL_HOST_USER = "dwqd853@gmail.com"  # 寄件者電子郵件
# EMAIL_HOST_PASSWORD = "siffxzyxustfspze"  # Gmail應用程式的密碼

# Redis Cache
# see: https://django-redis-chs.readthedocs.io/zh_CN/latest/
if env("DJANGO_REDIS_ENABLE", default=False):
    REDIS_URL = f"redis://:{env('DJANGO_REDIS_PASSWORD')}@{env('DJANGO_REDIS_HOST')}:{env('DJANGO_REDIS_PORT')}"

    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": f"{REDIS_URL}/{env('DJANGO_REDIS_DB')}",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": {"max_connections": 100},
                "PASSWORD": env("DJANGO_REDIS_PASSWORD"),
            },
        }
    }

    # Using Redis cache session login
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"

# Test running middleware
# https://stackoverflow.com/a/15890638
TEST_MODE = False
TEST_RUNNER = "base.middleware.test_suite_runner.TestSuiteRunner"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "normal": {"format": "[%(levelname)s] %(asctime)s | %(module)s | %(name)s:%(lineno)d | %(message)s"},
        "simple": {"format": "[%(levelname)s] %(message)s"},
    },
    "filters": {
        # 'special': {
        #     '()': 'project.logging.SpecialFilter',
        #     'foo': 'bar',
        # },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "normal",
        },
        "django_uwsgi": {
            "filters": ["require_debug_false"],
            "class": "logging.handlers.WatchedFileHandler",
            "formatter": "normal",
            "filename": BASE_DIR / "../logs/uwsgi.log",
        },
        # "mail_admins": {
        #     "level": "ERROR",
        #     "class": "django.utils.log.AdminEmailHandler",
        #     "formatter": "normal",
        # },
        "file": {
            "level": "INFO",
            "filters": ["require_debug_true"],
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": BASE_DIR / "../logs/django.log",
            "formatter": "normal",
            "when": "midnight",  # 每天凌晨
            "backupCount": 7,  # 保留7天
            "encoding": "utf-8",  # 使用utf-8編碼
            "interval": 1,  # 1 day
        },
        "error": {
            "level": "ERROR",
            "filters": ["require_debug_true"],
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": BASE_DIR / "../logs/django_error.log",
            "formatter": "normal",
            "when": "midnight",  # 每天凌晨
            "backupCount": 7,  # 保留7天
            "encoding": "utf-8",  # 使用utf-8編碼
            "interval": 1,  # 1 day
        },
    },
    "loggers": {
        "": {
            "handlers": ["console", "django_uwsgi", "file", "error"],
        },
        "django": {
            "handlers": ["console", "django_uwsgi", "file", "error"],
            "level": "INFO",
        },
        "django.server": {
            "handlers": ["django_uwsgi", "file", "error"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["django_uwsgi", "file", "error"],
            "level": "INFO",
            "propagate": False,
        },
        # "myproject.custom": {
        #     "handlers": ["console", "mail_admins"],
        #     "level": "INFO",
        #     "filters": ["special"],
        # },
    },
}

# CORS
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = (
    "http://127.0.0.1:3002",
    "http://localhost:3002",
    "http://127.0.0.1:3005",
    "http://localhost:3005",
    "http://django:3003",
    f"http://{env('BACKEND_HOST')}:{env('BACKEND_PORT')}",
    env("BACKEND_DOMAIN"),
)
CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
    "VIEW",
)
CORS_ALLOW_HEADERS = [
    "XMLHttpRequest",
    "X_FILENAME",
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "X-CSRFTOKEN",
    "x-requested-with",
]


# Partition table manager
PSQLEXTRA_PARTITIONING_MANAGER = "log.partition.manager"


# Go api server
GO_API_SERVER_HOST = env("GO_API_SERVER_HOST")
GO_API_SERVER_PORT = env("GO_API_SERVER_PORT")
GO_DB_SCHEMA = env("GO_DB_SCHEMA")

# role permission
ROLEPERMISSIONS_MODULE = "base.roles"
